---
title: "Array of things"
output: html_notebook
---

The URL of the 'Array of things' dataset on Socrata is: https://data.cityofchicago.org/resource/dbwu-caep.<extension>

Ingestion of data is done

```{r}

# Load the 'Array of things' dataset on Socrata into a DataFrame
df <- read.csv("http://data.cityofchicago.org/resource/dbwu-caep.csv")

head(df)
```

In python (and pandas) it is:

```{python}
import pandas as pd

# Load the 'Array of things' dataset on Socrata into a DataFrame
AoT_url = "http://data.cityofchicago.org/resource/dbwu-caep.csv"
df = pd.read_csv(AoT_url)

df.head()
#df.describe()
#df.shape
```

Let's remove the useless columns and leave only the 6, 7, 12, 14, 15, 16, 17.

```{r}
# The list of useful columns
useful <- c(7, 14, 15, 12, 6, 17, 16)

# The Useful DataFrame has only them (in a modified order)
udf <-df[, useful]
```

Now we need to extract the list of categories and only leave the live sensors in the Useful DataFrame

```{r}
# Form a vector of unique elements of the "category" column
catlist <- unique(udf[,"category"])

#ludf <- udf[ which(status=='Live'),]
ludf <- subset( udf, status=='Live', select = c(latitude:category, notes))

head(ludf)
```

